language: python

python:
    - "2.6"
    - "2.7"

env:
    - DJANGO=1.4.10
    - DJANGO=1.5.5
    - DJANGO=1.6.1

install:
    - pip install -q coveralls django==$DJANGO --use-mirrors
    - pip install flake8

before_script:
    - flake8 preserialize

script:
    - coverage run test_suite.py

after_success:
    - coveralls
